# Copyright 2023 Fortescue Metals Group Ltd. All rights reserved
#
# Override configuration for Redis for field.
#
# Some of the variables which can be inserted set by ImperiumServices::init_config_values()

dynaconf_merge: true
docker_services:
  redis_Field:
    # Only used for field, do not start by default.
    do_not_start: True
    image: "#{artifactory-repo}/docker-ams-fms-thirdparty/redis:6.2.6"
    ports:
      6379/tcp: "@format {this.override.redis.field_port}"
    environment:
      TZ: Australia/Perth
    detach: true
    remove: true
    start_string: Ready to accept connections
    run_options:
      - local
      - docker